/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6edc14f72e2f
 */

import { groupsList } from "../../funcs/groupsList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListConfigGroupByProductRequest$inboundSchema,
};

export const tool$groupsList: ToolDefinition<typeof args> = {
  name: "groups-list",
  description:
    `List all Worker Groups, Outpost Groups, or Edge Fleets for the specified Cribl product

Get a list of all Worker Groups, Outpost Groups, or Edge Fleets for the specified Cribl product.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await groupsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
