/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bf6c7e3b0c85
 */

import { pipelinesDelete } from "../../funcs/pipelinesDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeletePipelinesByIdRequest$inboundSchema,
};

export const tool$pipelinesDelete: ToolDefinition<typeof args> = {
  name: "pipelines-delete",
  description: `Delete a Pipeline

Delete the specified Pipeline.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await pipelinesDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
