openapi: 3.0.2
servers:
  - url: /
info:
  title: Cribl API Reference
  description: This API Reference lists available REST endpoints, along with their supported operations for accessing, creating, updating, or deleting resources. See our complementary product documentation at [docs.cribl.io](http://docs.cribl.io).
  version: 4.12.2-4b17c8d4
  contact:
    name: Support
    email: support@cribl.io
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    clientOauth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://login.cribl.cloud/oauth/token
          scopes: {}
  schemas:
    LoginInfo:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    AuthToken:
      type: object
      required:
        - token
      properties:
        token:
          type: string
    HealthStatus:
      type: object
      required:
        - status
        - startTime
      properties:
        role:
          type: string
          x-speakeasy-unknown-values: allow
          enum:
            - primary
            - standby
        status:
          type: string
          x-speakeasy-unknown-values: allow
          enum:
            - healthy
            - shutting down
            - standby
        startTime:
          type: number
security:
  - bearerAuth: []
  - clientOauth: []
tags:
  - name: auth
    description: Actions related to authentication. Do not use the /auth endpoints in Cribl.Cloud deployments. Instead, follow the instructions at https://docs.cribl.io/stream/api-tutorials/#criblcloud to authenticate for Cribl.Cloud.
  - name: diag
    description: Actions related to diagnostics
  - name: health
    description: Actions related to REST server health
paths:
  /auth/login:
    post:
      operationId: login
      summary: Log in and obtain Auth token
      description: This endpoint is unavailable on Cribl.Cloud. Instead, follow the instructions at https://docs.cribl.io/stream/api-tutorials/#criblcloud to get an Auth token for Cribl.Cloud.
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginInfo"
      security: []
      responses:
        "200":
          description: Authentication token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthToken"
        "401":
          description: Unauthorized
        "403":
          description: Access denied
        "429":
          description: Rate limit exceeded
  /health:
    get:
      operationId: getHealthInfo
      summary: Provides health info for REST server
      security: []
      tags:
        - diag
        - health
      responses:
        "200":
          description: Healthy status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthStatus"
        "420":
          description: Shutting Down or Standby status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthStatus"
