workflowVersion: 1.0.0
speakeasyVersion: 1.585.0
sources:
    Cribl API Reference:
        inputs:
            - location: https://raw.githubusercontent.com/criblio/cribl-openapi-spec/main/specs/control-plane.yml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/cribl/cribl/cribl-api-reference
    Cribl API Reference Dev:
        inputs:
            - location: https://raw.githubusercontent.com/criblio/cribl-openapi-spec/main/specs/control-plane-prerelease.yml
        registry:
            location: registry.speakeasyapi.dev/cribl/cribl/cribl-api-reference-dev
targets:
    cribl-control-plane:
        target: typescript
        source: Cribl API Reference
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/cribl/cribl/cribl-api-reference-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
        testing:
            enabled: true
    cribl-control-plane-dev:
        target: typescript
        source: Cribl API Reference Dev
        publish:
            npm:
                token: $npm_token
