/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * a list of string objects
 */
export type CreateVersionPushResponse = {
  /**
   * number of items present in the items array
   */
  count?: number | undefined;
  items?: Array<string> | undefined;
};

/** @internal */
export const CreateVersionPushResponse$inboundSchema: z.ZodType<
  CreateVersionPushResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  count: z.number().int().optional(),
  items: z.array(z.string()).optional(),
});

export function createVersionPushResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateVersionPushResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateVersionPushResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateVersionPushResponse' from JSON`,
  );
}
