/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteOutputByIdRequest = {
  /**
   * The <code>id</code> of the Destination to delete.
   */
  id: string;
};

/** @internal */
export const DeleteOutputByIdRequest$inboundSchema: z.ZodType<
  DeleteOutputByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: types.string(),
});
/** @internal */
export type DeleteOutputByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteOutputByIdRequest$outboundSchema: z.ZodType<
  DeleteOutputByIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteOutputByIdRequest
> = z.object({
  id: z.string(),
});

export function deleteOutputByIdRequestToJSON(
  deleteOutputByIdRequest: DeleteOutputByIdRequest,
): string {
  return JSON.stringify(
    DeleteOutputByIdRequest$outboundSchema.parse(deleteOutputByIdRequest),
  );
}
export function deleteOutputByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteOutputByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteOutputByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteOutputByIdRequest' from JSON`,
  );
}
