/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * Filter datasets by format. Set to <code>ddss</code> to return only DDSS datasets.
 */
export const GetCriblLakeDatasetByLakeIdFormat = {
  Ddss: "ddss",
} as const;
/**
 * Filter datasets by format. Set to <code>ddss</code> to return only DDSS datasets.
 */
export type GetCriblLakeDatasetByLakeIdFormat = OpenEnum<
  typeof GetCriblLakeDatasetByLakeIdFormat
>;

export type GetCriblLakeDatasetByLakeIdRequest = {
  /**
   * The <code>id</code> of the Lake that contains the Lake Datasets to list.
   */
  lakeId: string;
  /**
   * Filter datasets by storage location ID. Use <code>default</code> for default storage location.
   */
  storageLocationId?: string | undefined;
  /**
   * Filter datasets by format. Set to <code>ddss</code> to return only DDSS datasets.
   */
  format?: GetCriblLakeDatasetByLakeIdFormat | undefined;
  /**
   * Exclude DDSS format datasets from the response.
   */
  excludeDDSS?: boolean | undefined;
  /**
   * Exclude Netskope format datasets from the response.
   */
  excludeNetskope?: boolean | undefined;
  /**
   * Exclude deleted datasets from the response.
   */
  excludeDeleted?: boolean | undefined;
  /**
   * Exclude internal datasets (those with IDs starting with <code>cribl_</code>) from the response.
   */
  excludeInternal?: boolean | undefined;
  /**
   * Exclude BYOS (Bring Your Own Storage) datasets from the response.
   */
  excludeBYOS?: boolean | undefined;
  /**
   * Set to <code>true</code> to include storage metrics for each Lake Dataset. Otherwise, <code>false</code> (default). Requires a Cribl Lake metrics license.
   */
  includeMetrics?: boolean | undefined;
  /**
   * Pagination offset
   */
  offset?: number | undefined;
  /**
   * Maximum number of items to return
   */
  limit?: number | undefined;
};

export type GetCriblLakeDatasetByLakeIdResponse = {
  result: models.PaginatedCriblLakeDataset;
};

/** @internal */
export const GetCriblLakeDatasetByLakeIdFormat$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  GetCriblLakeDatasetByLakeIdFormat
> = openEnums.outboundSchema(GetCriblLakeDatasetByLakeIdFormat);

/** @internal */
export type GetCriblLakeDatasetByLakeIdRequest$Outbound = {
  lakeId: string;
  storageLocationId?: string | undefined;
  format?: string | undefined;
  excludeDDSS?: boolean | undefined;
  excludeNetskope?: boolean | undefined;
  excludeDeleted?: boolean | undefined;
  excludeInternal?: boolean | undefined;
  excludeBYOS?: boolean | undefined;
  includeMetrics?: boolean | undefined;
  offset?: number | undefined;
  limit?: number | undefined;
};

/** @internal */
export const GetCriblLakeDatasetByLakeIdRequest$outboundSchema: z.ZodType<
  GetCriblLakeDatasetByLakeIdRequest$Outbound,
  z.ZodTypeDef,
  GetCriblLakeDatasetByLakeIdRequest
> = z.object({
  lakeId: z.string(),
  storageLocationId: z.string().optional(),
  format: GetCriblLakeDatasetByLakeIdFormat$outboundSchema.optional(),
  excludeDDSS: z.boolean().optional(),
  excludeNetskope: z.boolean().optional(),
  excludeDeleted: z.boolean().optional(),
  excludeInternal: z.boolean().optional(),
  excludeBYOS: z.boolean().optional(),
  includeMetrics: z.boolean().optional(),
  offset: z.number().int().optional(),
  limit: z.number().int().optional(),
});

export function getCriblLakeDatasetByLakeIdRequestToJSON(
  getCriblLakeDatasetByLakeIdRequest: GetCriblLakeDatasetByLakeIdRequest,
): string {
  return JSON.stringify(
    GetCriblLakeDatasetByLakeIdRequest$outboundSchema.parse(
      getCriblLakeDatasetByLakeIdRequest,
    ),
  );
}

/** @internal */
export const GetCriblLakeDatasetByLakeIdResponse$inboundSchema: z.ZodType<
  GetCriblLakeDatasetByLakeIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: models.PaginatedCriblLakeDataset$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

export function getCriblLakeDatasetByLakeIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCriblLakeDatasetByLakeIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetCriblLakeDatasetByLakeIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCriblLakeDatasetByLakeIdResponse' from JSON`,
  );
}
