/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 65feac3b3260
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetRoutesByPackAndIdRequest = {
  /**
   * The <code>id</code> of the Routing table to get. The supported value is <code>default</code>.
   */
  id: string;
  /**
   * The <code>id</code> of the Pack to get.
   */
  pack: string;
};

/** @internal */
export const GetRoutesByPackAndIdRequest$inboundSchema: z.ZodType<
  GetRoutesByPackAndIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: types.string(),
  pack: types.string(),
});
/** @internal */
export type GetRoutesByPackAndIdRequest$Outbound = {
  id: string;
  pack: string;
};

/** @internal */
export const GetRoutesByPackAndIdRequest$outboundSchema: z.ZodType<
  GetRoutesByPackAndIdRequest$Outbound,
  z.ZodTypeDef,
  GetRoutesByPackAndIdRequest
> = z.object({
  id: z.string(),
  pack: z.string(),
});

export function getRoutesByPackAndIdRequestToJSON(
  getRoutesByPackAndIdRequest: GetRoutesByPackAndIdRequest,
): string {
  return JSON.stringify(
    GetRoutesByPackAndIdRequest$outboundSchema.parse(
      getRoutesByPackAndIdRequest,
    ),
  );
}
export function getRoutesByPackAndIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetRoutesByPackAndIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetRoutesByPackAndIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRoutesByPackAndIdRequest' from JSON`,
  );
}
