/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6eadfdb4717a
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateSavedJobByIdRequest = {
  /**
   * The <code>id</code> of the Collector to update.
   */
  id: string;
  /**
   * SavedJob object
   */
  savedJob: models.SavedJob;
};

/** @internal */
export type UpdateSavedJobByIdRequest$Outbound = {
  id: string;
  SavedJob: models.SavedJob$Outbound;
};

/** @internal */
export const UpdateSavedJobByIdRequest$outboundSchema: z.ZodType<
  UpdateSavedJobByIdRequest$Outbound,
  z.ZodTypeDef,
  UpdateSavedJobByIdRequest
> = z.object({
  id: z.string(),
  savedJob: models.SavedJob$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    savedJob: "SavedJob",
  });
});

export function updateSavedJobByIdRequestToJSON(
  updateSavedJobByIdRequest: UpdateSavedJobByIdRequest,
): string {
  return JSON.stringify(
    UpdateSavedJobByIdRequest$outboundSchema.parse(updateSavedJobByIdRequest),
  );
}
