/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateOutputSystemByPackAndIdRequest = {
  /**
   * The <code>id</code> of the Destination to update.
   */
  id: string;
  /**
   * The <code>id</code> of the Pack to update.
   */
  pack: string;
  /**
   * Output object
   */
  output: models.Output;
};

/** @internal */
export type UpdateOutputSystemByPackAndIdRequest$Outbound = {
  id: string;
  pack: string;
  Output: models.Output$Outbound;
};

/** @internal */
export const UpdateOutputSystemByPackAndIdRequest$outboundSchema: z.ZodType<
  UpdateOutputSystemByPackAndIdRequest$Outbound,
  z.ZodTypeDef,
  UpdateOutputSystemByPackAndIdRequest
> = z.object({
  id: z.string(),
  pack: z.string(),
  output: models.Output$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    output: "Output",
  });
});

export function updateOutputSystemByPackAndIdRequestToJSON(
  updateOutputSystemByPackAndIdRequest: UpdateOutputSystemByPackAndIdRequest,
): string {
  return JSON.stringify(
    UpdateOutputSystemByPackAndIdRequest$outboundSchema.parse(
      updateOutputSystemByPackAndIdRequest,
    ),
  );
}
