/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * Authentication method.
 */
export const AuthenticationMethodOptionse9c778 = {
  /**
   * Manual
   */
  Manual: "manual",
  /**
   * Secret Key pair
   */
  Secret: "secret",
} as const;
/**
 * Authentication method.
 */
export type AuthenticationMethodOptionse9c778 = OpenEnum<
  typeof AuthenticationMethodOptionse9c778
>;

/** @internal */
export const AuthenticationMethodOptionse9c778$inboundSchema: z.ZodType<
  AuthenticationMethodOptionse9c778,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(AuthenticationMethodOptionse9c778);
/** @internal */
export const AuthenticationMethodOptionse9c778$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  AuthenticationMethodOptionse9c778
> = openEnums.outboundSchema(AuthenticationMethodOptionse9c778);
