/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  CollectorConf,
  CollectorConf$inboundSchema,
  CollectorConf$Outbound,
  CollectorConf$outboundSchema,
} from "./collectorconf.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CollectorTypeSavedJobCollection = {
  /**
   * The type of collector to run
   */
  type: string;
  /**
   * Collector configuration
   */
  conf: CollectorConf;
  /**
   * Delete any files collected (where applicable)
   */
  destructive?: boolean | undefined;
  /**
   * Character encoding to use when parsing ingested data. When not set, @{product} will default to UTF-8 but may incorrectly interpret multi-byte characters.
   */
  encoding?: string | undefined;
};

/** @internal */
export const CollectorTypeSavedJobCollection$inboundSchema: z.ZodType<
  CollectorTypeSavedJobCollection,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.string(),
  conf: CollectorConf$inboundSchema,
  destructive: z.boolean().default(false),
  encoding: z.string().optional(),
});
/** @internal */
export type CollectorTypeSavedJobCollection$Outbound = {
  type: string;
  conf: CollectorConf$Outbound;
  destructive: boolean;
  encoding?: string | undefined;
};

/** @internal */
export const CollectorTypeSavedJobCollection$outboundSchema: z.ZodType<
  CollectorTypeSavedJobCollection$Outbound,
  z.ZodTypeDef,
  CollectorTypeSavedJobCollection
> = z.object({
  type: z.string(),
  conf: CollectorConf$outboundSchema,
  destructive: z.boolean().default(false),
  encoding: z.string().optional(),
});

export function collectorTypeSavedJobCollectionToJSON(
  collectorTypeSavedJobCollection: CollectorTypeSavedJobCollection,
): string {
  return JSON.stringify(
    CollectorTypeSavedJobCollection$outboundSchema.parse(
      collectorTypeSavedJobCollection,
    ),
  );
}
export function collectorTypeSavedJobCollectionFromJSON(
  jsonString: string,
): SafeParseResult<CollectorTypeSavedJobCollection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CollectorTypeSavedJobCollection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CollectorTypeSavedJobCollection' from JSON`,
  );
}
