/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * Codec to use to compress the persisted data
 */
export const CompressionOptionsPq = {
  /**
   * None
   */
  None: "none",
  /**
   * Gzip
   */
  Gzip: "gzip",
} as const;
/**
 * Codec to use to compress the persisted data
 */
export type CompressionOptionsPq = OpenEnum<typeof CompressionOptionsPq>;

/** @internal */
export const CompressionOptionsPq$inboundSchema: z.ZodType<
  CompressionOptionsPq,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(CompressionOptionsPq);
/** @internal */
export const CompressionOptionsPq$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  CompressionOptionsPq
> = openEnums.outboundSchema(CompressionOptionsPq);
