/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  Commit,
  Commit$inboundSchema,
  Commit$Outbound,
  Commit$outboundSchema,
} from "./commit.js";
import {
  ConfigGroupCloud,
  ConfigGroupCloud$inboundSchema,
  ConfigGroupCloud$Outbound,
  ConfigGroupCloud$outboundSchema,
} from "./configgroupcloud.js";
import {
  ConfigGroupLookups,
  ConfigGroupLookups$inboundSchema,
  ConfigGroupLookups$Outbound,
  ConfigGroupLookups$outboundSchema,
} from "./configgrouplookups.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  EstimatedIngestRateOptionsConfigGroup,
  EstimatedIngestRateOptionsConfigGroup$inboundSchema,
  EstimatedIngestRateOptionsConfigGroup$outboundSchema,
} from "./estimatedingestrateoptionsconfiggroup.js";
import {
  TypeOptionsConfigGroup,
  TypeOptionsConfigGroup$inboundSchema,
  TypeOptionsConfigGroup$outboundSchema,
} from "./typeoptionsconfiggroup.js";

/**
 * Git status of the Worker Group, Outpost Group, or Edge Fleet configuration. Automatically populated and returned in responses.
 */
export type Git = {
  /**
   * Commit hash of the currently committed configuration version.
   */
  commit?: string | undefined;
  /**
   * Number of local configuration changes not yet committed.
   */
  localChanges?: number | undefined;
  /**
   * List of recent configuration commits.
   */
  log?: Array<Commit> | undefined;
};

export type ConfigGroup = {
  cloud?: ConfigGroupCloud | undefined;
  /**
   * Commit hash of the deployed configuration version for the Worker Group, Outpost Group, or Edge Fleet. Automatically populated and returned in responses.<br/><br/> **Warning**: Do not change the value of <code>configVersion</code> in the body of PATCH requests. The PATCH request body must include the value as it appears in the <code>GET /products/{product}/groups/{id}</code> response.
   */
  configVersion?: string | undefined;
  /**
   * Number of Workers or Nodes that are currently deploying the latest configuration version.<br/><br/> **Warning**: Do not change the value of <code>deployingWorkerCount</code> in the body of PATCH requests. The PATCH request body must include the value as it appears in the <code>GET /products/{product}/groups/{id}</code> response.
   */
  deployingWorkerCount?: number | undefined;
  /**
   * Brief description of the Worker Group, Outpost Group, or Edge Fleet.
   */
  description?: string | undefined;
  /**
   * Estimated ingest rate for a Cribl.Cloud Worker Group, in GB/sec.
   */
  estimatedIngestRate?: EstimatedIngestRateOptionsConfigGroup | undefined;
  /**
   * Git status of the Worker Group, Outpost Group, or Edge Fleet configuration. Automatically populated and returned in responses.
   */
  git?: Git | undefined;
  id: string;
  /**
   * Number of Workers or Nodes running a Cribl version that is incompatible with the current upgrade target.<br/><br/> **Warning**: Do not change the value of <code>incompatibleWorkerCount</code> in the body of PATCH requests. The PATCH request body must include the value as it appears in the <code>GET /products/{product}/groups/{id}</code> response.
   */
  incompatibleWorkerCount?: number | undefined;
  /**
   * The <code>id</code> of the parent Edge Fleet. If provided, this Fleet inherits configuration from the specified parent Fleet. Applies only to Edge Fleets.
   */
  inherits?: string | undefined;
  /**
   * Indicates whether this is an Edge Fleet. Deprecated. Use to identify Edge Fleets.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  isFleet?: boolean | undefined;
  /**
   * Indicates whether this is an internal Search Group. Deprecated. Use to identify Search Groups.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  isSearch?: boolean | undefined;
  /**
   * Lookup deployment status per Worker or Node context.<br/><br/> **Warning**: Do not change the value of <code>lookupDeployments</code> in the body of PATCH requests. The PATCH request body must include the value as it appears in the <code>GET /products/{product}/groups/{id}</code> response.
   */
  lookupDeployments?: Array<ConfigGroupLookups> | undefined;
  /**
   * Maximum duration a Worker or Node can remain disconnected before the Leader removes it. The value is a numeral with units, such as <code>8h</code>, <code>5d</code>, <code>1w</code>.
   */
  maxWorkerAge?: string | undefined;
  /**
   * Name of the Worker Group, Outpost Group, or Edge Fleet.
   */
  name?: string | undefined;
  /**
   * If <code>true</code>, the Worker Group, Outpost Group, or Edge Fleet uses customer-hosted (on-prem) workers. If <code>false</code>, the Worker Group, Outpost Group, or Edge Fleet is managed in Cribl.Cloud.
   */
  onPrem?: boolean | undefined;
  /**
   * If <code>true</code>, the Cribl.Cloud Worker Group has active Workers provisioned. Applies only to Cribl.Cloud Worker Groups.
   */
  provisioned?: boolean | undefined;
  /**
   * Metadata tags attached to the Worker Group, Outpost Group, or Edge Fleet for categorization, filtering, and tag-based routing and policy application. Useful for organizing Groups and Fleets and enabling tag-driven workflows in Cribl.
   */
  streamtags?: Array<string> | undefined;
  /**
   * Legacy system-level tags associated with the Worker Group, Outpost Group, or Edge Fleet. Use <code>streamtags</code> instead.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  tags?: string | undefined;
  /**
   * Explicit type of the Worker Group, Outpost Group, or Edge Fleet.
   */
  type?: TypeOptionsConfigGroup | undefined;
  /**
   * Target software upgrade version. Applies only to Outpost Groups and Edge Fleets.
   */
  upgradeVersion?: string | undefined;
  /**
   * Number of Workers or Nodes currently in the Worker Group, Outpost Group, or Edge Fleet. The value is automatically populated and **does not scale Cribl.Cloud Worker Groups**. Use <code>estimatedIngestRate</code> to scale Cribl.Cloud Worker Groups. <br/><br/> **Warning**: Do not change the value of <code>workerCount</code> in the body of PATCH requests. The PATCH request body must include the value as it appears in the <code>GET /products/{product}/groups/{id}</code> response.
   */
  workerCount?: number | undefined;
  /**
   * If <code>true</code>, the Leader allows remote access (teleporting) into the Workers or Nodes of the Worker Group, Outpost Group, or Edge Fleet.
   */
  workerRemoteAccess?: boolean | undefined;
};

/** @internal */
export const Git$inboundSchema: z.ZodType<Git, z.ZodTypeDef, unknown> = z
  .object({
    commit: types.optional(types.string()),
    localChanges: types.optional(types.number()),
    log: types.optional(z.array(Commit$inboundSchema)),
  });
/** @internal */
export type Git$Outbound = {
  commit?: string | undefined;
  localChanges?: number | undefined;
  log?: Array<Commit$Outbound> | undefined;
};

/** @internal */
export const Git$outboundSchema: z.ZodType<Git$Outbound, z.ZodTypeDef, Git> = z
  .object({
    commit: z.string().optional(),
    localChanges: z.number().int().optional(),
    log: z.array(Commit$outboundSchema).optional(),
  });

export function gitToJSON(git: Git): string {
  return JSON.stringify(Git$outboundSchema.parse(git));
}
export function gitFromJSON(
  jsonString: string,
): SafeParseResult<Git, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Git$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Git' from JSON`,
  );
}

/** @internal */
export const ConfigGroup$inboundSchema: z.ZodType<
  ConfigGroup,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud: types.optional(ConfigGroupCloud$inboundSchema),
  configVersion: types.optional(types.string()),
  deployingWorkerCount: types.optional(types.number()),
  description: types.optional(types.string()),
  estimatedIngestRate: types.optional(
    EstimatedIngestRateOptionsConfigGroup$inboundSchema,
  ),
  git: types.optional(z.lazy(() => Git$inboundSchema)),
  id: types.string(),
  incompatibleWorkerCount: types.optional(types.number()),
  inherits: types.optional(types.string()),
  isFleet: types.optional(types.boolean()),
  isSearch: types.optional(types.boolean()),
  lookupDeployments: types.optional(z.array(ConfigGroupLookups$inboundSchema)),
  maxWorkerAge: types.optional(types.string()),
  name: types.optional(types.string()),
  onPrem: types.optional(types.boolean()),
  provisioned: types.optional(types.boolean()),
  streamtags: types.optional(z.array(types.string())),
  tags: types.optional(types.string()),
  type: types.optional(TypeOptionsConfigGroup$inboundSchema),
  upgradeVersion: types.optional(types.string()),
  workerCount: types.optional(types.number()),
  workerRemoteAccess: types.optional(types.boolean()),
});
/** @internal */
export type ConfigGroup$Outbound = {
  cloud?: ConfigGroupCloud$Outbound | undefined;
  configVersion?: string | undefined;
  deployingWorkerCount?: number | undefined;
  description?: string | undefined;
  estimatedIngestRate?: number | undefined;
  git?: Git$Outbound | undefined;
  id: string;
  incompatibleWorkerCount?: number | undefined;
  inherits?: string | undefined;
  isFleet?: boolean | undefined;
  isSearch?: boolean | undefined;
  lookupDeployments?: Array<ConfigGroupLookups$Outbound> | undefined;
  maxWorkerAge?: string | undefined;
  name?: string | undefined;
  onPrem?: boolean | undefined;
  provisioned?: boolean | undefined;
  streamtags?: Array<string> | undefined;
  tags?: string | undefined;
  type?: string | undefined;
  upgradeVersion?: string | undefined;
  workerCount?: number | undefined;
  workerRemoteAccess?: boolean | undefined;
};

/** @internal */
export const ConfigGroup$outboundSchema: z.ZodType<
  ConfigGroup$Outbound,
  z.ZodTypeDef,
  ConfigGroup
> = z.object({
  cloud: ConfigGroupCloud$outboundSchema.optional(),
  configVersion: z.string().optional(),
  deployingWorkerCount: z.number().int().optional(),
  description: z.string().optional(),
  estimatedIngestRate: EstimatedIngestRateOptionsConfigGroup$outboundSchema
    .optional(),
  git: z.lazy(() => Git$outboundSchema).optional(),
  id: z.string(),
  incompatibleWorkerCount: z.number().int().optional(),
  inherits: z.string().optional(),
  isFleet: z.boolean().optional(),
  isSearch: z.boolean().optional(),
  lookupDeployments: z.array(ConfigGroupLookups$outboundSchema).optional(),
  maxWorkerAge: z.string().optional(),
  name: z.string().optional(),
  onPrem: z.boolean().optional(),
  provisioned: z.boolean().optional(),
  streamtags: z.array(z.string()).optional(),
  tags: z.string().optional(),
  type: TypeOptionsConfigGroup$outboundSchema.optional(),
  upgradeVersion: z.string().optional(),
  workerCount: z.number().int().optional(),
  workerRemoteAccess: z.boolean().optional(),
});

export function configGroupToJSON(configGroup: ConfigGroup): string {
  return JSON.stringify(ConfigGroup$outboundSchema.parse(configGroup));
}
export function configGroupFromJSON(
  jsonString: string,
): SafeParseResult<ConfigGroup, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConfigGroup$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConfigGroup' from JSON`,
  );
}
