/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type EventBreakerRuleFields = {
  name: string;
  value: string;
};

/** @internal */
export type EventBreakerRuleFields$Outbound = {
  name: string;
  value: string;
};

/** @internal */
export const EventBreakerRuleFields$outboundSchema: z.ZodType<
  EventBreakerRuleFields$Outbound,
  z.ZodTypeDef,
  EventBreakerRuleFields
> = z.object({
  name: z.string(),
  value: z.string(),
});

export function eventBreakerRuleFieldsToJSON(
  eventBreakerRuleFields: EventBreakerRuleFields,
): string {
  return JSON.stringify(
    EventBreakerRuleFields$outboundSchema.parse(eventBreakerRuleFields),
  );
}
