/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  catchUnrecognizedEnum,
  OpenEnum,
  Unrecognized,
} from "../types/enums.js";

/**
 * Format of the output data
 */
export const Format1Options = {
  /**
   * JSON
   */
  Json: "json",
  /**
   * Raw
   */
  Raw: "raw",
  /**
   * Parquet
   */
  Parquet: "parquet",
} as const;
/**
 * Format of the output data
 */
export type Format1Options = OpenEnum<typeof Format1Options>;

/** @internal */
export const Format1Options$inboundSchema: z.ZodType<
  Format1Options,
  z.ZodTypeDef,
  unknown
> = z
  .union([
    z.nativeEnum(Format1Options),
    z.string().transform(catchUnrecognizedEnum),
  ]);
/** @internal */
export const Format1Options$outboundSchema: z.ZodType<
  Format1Options,
  z.ZodTypeDef,
  Format1Options
> = z.union([
  z.nativeEnum(Format1Options),
  z.string().and(z.custom<Unrecognized<string>>()),
]);
