/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type FunctionDropConf = {};

export const FunctionDropId = {
  Drop: "drop",
} as const;
export type FunctionDropId = ClosedEnum<typeof FunctionDropId>;

export type FunctionDrop = {
  conf: FunctionDropConf;
  filename: string;
  disabled: boolean;
  group: string;
  id: FunctionDropId;
  initTime: number;
  loadTime: number;
  modTime: number;
  name: string;
  /**
   * JSON Schema Draft-06
   */
  schema: { [k: string]: any };
  uischema: { [k: string]: any };
  version: string;
};

/** @internal */
export const FunctionDropConf$inboundSchema: z.ZodType<
  FunctionDropConf,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function functionDropConfFromJSON(
  jsonString: string,
): SafeParseResult<FunctionDropConf, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FunctionDropConf$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FunctionDropConf' from JSON`,
  );
}

/** @internal */
export const FunctionDropId$inboundSchema: z.ZodNativeEnum<
  typeof FunctionDropId
> = z.nativeEnum(FunctionDropId);

/** @internal */
export const FunctionDrop$inboundSchema: z.ZodType<
  FunctionDrop,
  z.ZodTypeDef,
  unknown
> = z.object({
  __conf: z.lazy(() => FunctionDropConf$inboundSchema),
  __filename: z.string(),
  disabled: z.boolean(),
  group: z.string(),
  id: FunctionDropId$inboundSchema,
  initTime: z.number(),
  loadTime: z.number(),
  modTime: z.number(),
  name: z.string(),
  schema: z.record(z.any()),
  uischema: z.record(z.any()),
  version: z.string(),
}).transform((v) => {
  return remap$(v, {
    "__conf": "conf",
    "__filename": "filename",
  });
});

export function functionDropFromJSON(
  jsonString: string,
): SafeParseResult<FunctionDrop, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FunctionDrop$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FunctionDrop' from JSON`,
  );
}
