/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const FunctionCommentId = {
  Comment: "comment",
} as const;
export type FunctionCommentId = ClosedEnum<typeof FunctionCommentId>;

export type FunctionCommentSchema = {
  /**
   * Optional, short description of this Function's purpose in the Pipeline
   */
  comment?: string | undefined;
};

export type FunctionComment = {
  filename: string;
  asyncTimeout?: number | undefined;
  criblVersion?: string | undefined;
  disabled: boolean;
  group: string;
  handleSignals?: boolean | undefined;
  id: FunctionCommentId;
  loadTime: number;
  modTime: number;
  name: string;
  sync?: boolean | undefined;
  uischema: { [k: string]: any };
  version: string;
  schema?: FunctionCommentSchema | undefined;
};

/** @internal */
export const FunctionCommentId$inboundSchema: z.ZodNativeEnum<
  typeof FunctionCommentId
> = z.nativeEnum(FunctionCommentId);

/** @internal */
export const FunctionCommentSchema$inboundSchema: z.ZodType<
  FunctionCommentSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  comment: z.string().optional(),
});

export function functionCommentSchemaFromJSON(
  jsonString: string,
): SafeParseResult<FunctionCommentSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FunctionCommentSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FunctionCommentSchema' from JSON`,
  );
}

/** @internal */
export const FunctionComment$inboundSchema: z.ZodType<
  FunctionComment,
  z.ZodTypeDef,
  unknown
> = z.object({
  __filename: z.string(),
  asyncTimeout: z.number().optional(),
  cribl_version: z.string().optional(),
  disabled: z.boolean(),
  group: z.string(),
  handleSignals: z.boolean().optional(),
  id: FunctionCommentId$inboundSchema,
  loadTime: z.number(),
  modTime: z.number(),
  name: z.string(),
  sync: z.boolean().optional(),
  uischema: z.record(z.any()),
  version: z.string(),
  schema: z.lazy(() => FunctionCommentSchema$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "__filename": "filename",
    "cribl_version": "criblVersion",
  });
});

export function functionCommentFromJSON(
  jsonString: string,
): SafeParseResult<FunctionComment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FunctionComment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FunctionComment' from JSON`,
  );
}
