/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type FunctionNotifications = {
  __filename: string;
  asyncTimeout?: number | undefined;
  cribl_version?: string | undefined;
  disabled?: boolean | undefined;
  group: string;
  handleSignals?: boolean | undefined;
  id: "notifications";
  loadTime: number;
  modTime: number;
  name: string;
  sync?: boolean | undefined;
  uischema: { [k: string]: any };
  version: string;
  schema?: { [k: string]: any } | undefined;
};

/** @internal */
export const FunctionNotifications$inboundSchema: z.ZodType<
  FunctionNotifications,
  z.ZodTypeDef,
  unknown
> = z.object({
  __filename: z.string(),
  asyncTimeout: z.number().optional(),
  cribl_version: z.string().optional(),
  disabled: z.boolean().optional(),
  group: z.string(),
  handleSignals: z.boolean().optional(),
  id: z.literal("notifications"),
  loadTime: z.number(),
  modTime: z.number(),
  name: z.string(),
  sync: z.boolean().optional(),
  uischema: z.record(z.any()),
  version: z.string(),
  schema: z.record(z.any()).optional(),
});

export function functionNotificationsFromJSON(
  jsonString: string,
): SafeParseResult<FunctionNotifications, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FunctionNotifications$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FunctionNotifications' from JSON`,
  );
}
