/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type FunctionUnrollConf = {
  /**
   * Field in which to find/calculate the array to unroll. Example: _raw, _raw.split(/\n/)
   */
  srcExpr?: string | undefined;
  /**
   * Field in destination event in which to place the unrolled value
   */
  dstField?: string | undefined;
};

export const FunctionUnrollId = {
  Unroll: "unroll",
} as const;
export type FunctionUnrollId = ClosedEnum<typeof FunctionUnrollId>;

export type FunctionUnroll = {
  conf: FunctionUnrollConf;
  filename: string;
  disabled: boolean;
  group: string;
  id: FunctionUnrollId;
  initTime: number;
  loadTime: number;
  modTime: number;
  name: string;
  /**
   * JSON Schema Draft-06
   */
  schema: { [k: string]: any };
  uischema: { [k: string]: any };
  version: string;
};

/** @internal */
export const FunctionUnrollConf$inboundSchema: z.ZodType<
  FunctionUnrollConf,
  z.ZodTypeDef,
  unknown
> = z.object({
  srcExpr: z.string().default("_raw"),
  dstField: z.string().default("_raw"),
});

export function functionUnrollConfFromJSON(
  jsonString: string,
): SafeParseResult<FunctionUnrollConf, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FunctionUnrollConf$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FunctionUnrollConf' from JSON`,
  );
}

/** @internal */
export const FunctionUnrollId$inboundSchema: z.ZodNativeEnum<
  typeof FunctionUnrollId
> = z.nativeEnum(FunctionUnrollId);

/** @internal */
export const FunctionUnroll$inboundSchema: z.ZodType<
  FunctionUnroll,
  z.ZodTypeDef,
  unknown
> = z.object({
  __conf: z.lazy(() => FunctionUnrollConf$inboundSchema),
  __filename: z.string(),
  disabled: z.boolean(),
  group: z.string(),
  id: FunctionUnrollId$inboundSchema,
  initTime: z.number(),
  loadTime: z.number(),
  modTime: z.number(),
  name: z.string(),
  schema: z.record(z.any()),
  uischema: z.record(z.any()),
  version: z.string(),
}).transform((v) => {
  return remap$(v, {
    "__conf": "conf",
    "__filename": "filename",
  });
});

export function functionUnrollFromJSON(
  jsonString: string,
): SafeParseResult<FunctionUnroll, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FunctionUnroll$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FunctionUnroll' from JSON`,
  );
}
