/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Defines how sample rate will be derived: log(previousPeriodCount) or sqrt(previousPeriodCount)
 */
export const FunctionConfSchemaDynamicSamplingSampleMode = {
  /**
   * Logarithmic
   */
  Log: "log",
  /**
   * Square Root
   */
  Sqrt: "sqrt",
} as const;
/**
 * Defines how sample rate will be derived: log(previousPeriodCount) or sqrt(previousPeriodCount)
 */
export type FunctionConfSchemaDynamicSamplingSampleMode = OpenEnum<
  typeof FunctionConfSchemaDynamicSamplingSampleMode
>;

export type FunctionConfSchemaDynamicSampling = {
  /**
   * Defines how sample rate will be derived: log(previousPeriodCount) or sqrt(previousPeriodCount)
   */
  mode: FunctionConfSchemaDynamicSamplingSampleMode;
  /**
   * Expression used to derive sample group key. Example:`${domain}:${status}`. Each sample group will have its own derived sampling rate based on volume. Defaults to `${host}`.
   */
  keyExpr: string;
  /**
   * How often (in seconds) sample rates will be adjusted
   */
  samplePeriod: number;
  /**
   * Minimum number of events that must be received in previous sample period for sampling mode to be applied to current period. If the number of events received for a sample group is less than this minimum, a sample rate of 1:1 is used.
   */
  minEvents: number;
  /**
   * Maximum sampling rate. If computed sampling rate is above this value, it will be limited to this value.
   */
  maxSampleRate: number;
};

/** @internal */
export const FunctionConfSchemaDynamicSamplingSampleMode$inboundSchema:
  z.ZodType<
    FunctionConfSchemaDynamicSamplingSampleMode,
    z.ZodTypeDef,
    unknown
  > = openEnums.inboundSchema(FunctionConfSchemaDynamicSamplingSampleMode);

/** @internal */
export const FunctionConfSchemaDynamicSampling$inboundSchema: z.ZodType<
  FunctionConfSchemaDynamicSampling,
  z.ZodTypeDef,
  unknown
> = z.object({
  mode: FunctionConfSchemaDynamicSamplingSampleMode$inboundSchema.default(
    "log",
  ),
  keyExpr: z.string().default("`${host}`"),
  samplePeriod: z.number().default(30),
  minEvents: z.number().default(30),
  maxSampleRate: z.number().default(100),
});

export function functionConfSchemaDynamicSamplingFromJSON(
  jsonString: string,
): SafeParseResult<FunctionConfSchemaDynamicSampling, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FunctionConfSchemaDynamicSampling$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FunctionConfSchemaDynamicSampling' from JSON`,
  );
}
