/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ItemsTypeConnectionsOptional,
  ItemsTypeConnectionsOptional$inboundSchema,
  ItemsTypeConnectionsOptional$Outbound,
  ItemsTypeConnectionsOptional$outboundSchema,
} from "./itemstypeconnectionsoptional.js";
import {
  ItemsTypeNotificationMetadata,
  ItemsTypeNotificationMetadata$inboundSchema,
  ItemsTypeNotificationMetadata$Outbound,
  ItemsTypeNotificationMetadata$outboundSchema,
} from "./itemstypenotificationmetadata.js";
import {
  PqType,
  PqType$inboundSchema,
  PqType$Outbound,
  PqType$outboundSchema,
} from "./pqtype.js";

export type InputCriblmetrics = {
  /**
   * Unique ID for this input
   */
  id?: string | undefined;
  type: "criblmetrics";
  disabled?: boolean | undefined;
  /**
   * Pipeline to process data from this Source before sending it through the Routes
   */
  pipeline?: string | undefined;
  /**
   * Select whether to send data to Routes, or directly to Destinations.
   */
  sendToRoutes?: boolean | undefined;
  /**
   * Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere.
   */
  environment?: string | undefined;
  /**
   * Use a disk queue to minimize data loss when connected services block. See [Cribl Docs](https://docs.cribl.io/stream/persistent-queues) for PQ defaults (Cribl-managed Cloud Workers) and configuration options (on-prem and hybrid Workers).
   */
  pqEnabled?: boolean | undefined;
  /**
   * Tags for filtering and grouping in @{product}
   */
  streamtags?: Array<string> | undefined;
  /**
   * Direct connections to Destinations, and optionally via a Pipeline or a Pack
   */
  connections?: Array<ItemsTypeConnectionsOptional> | undefined;
  pq?: PqType | undefined;
  /**
   * A prefix that is applied to the metrics provided by Cribl Stream
   */
  prefix?: string | undefined;
  /**
   * Include granular metrics. Disabling this will drop the following metrics events: `cribl.logstream.host.(in_bytes,in_events,out_bytes,out_events)`, `cribl.logstream.index.(in_bytes,in_events,out_bytes,out_events)`, `cribl.logstream.source.(in_bytes,in_events,out_bytes,out_events)`, `cribl.logstream.sourcetype.(in_bytes,in_events,out_bytes,out_events)`.
   */
  fullFidelity?: boolean | undefined;
  /**
   * Fields to add to events from this input
   */
  metadata?: Array<ItemsTypeNotificationMetadata> | undefined;
  description?: string | undefined;
};

/** @internal */
export const InputCriblmetrics$inboundSchema: z.ZodType<
  InputCriblmetrics,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: types.optional(types.string()),
  type: types.literal("criblmetrics"),
  disabled: types.optional(types.boolean()),
  pipeline: types.optional(types.string()),
  sendToRoutes: types.optional(types.boolean()),
  environment: types.optional(types.string()),
  pqEnabled: types.optional(types.boolean()),
  streamtags: types.optional(z.array(types.string())),
  connections: types.optional(
    z.array(ItemsTypeConnectionsOptional$inboundSchema),
  ),
  pq: types.optional(PqType$inboundSchema),
  prefix: types.optional(types.string()),
  fullFidelity: types.optional(types.boolean()),
  metadata: types.optional(
    z.array(ItemsTypeNotificationMetadata$inboundSchema),
  ),
  description: types.optional(types.string()),
});
/** @internal */
export type InputCriblmetrics$Outbound = {
  id?: string | undefined;
  type: "criblmetrics";
  disabled?: boolean | undefined;
  pipeline?: string | undefined;
  sendToRoutes?: boolean | undefined;
  environment?: string | undefined;
  pqEnabled?: boolean | undefined;
  streamtags?: Array<string> | undefined;
  connections?: Array<ItemsTypeConnectionsOptional$Outbound> | undefined;
  pq?: PqType$Outbound | undefined;
  prefix?: string | undefined;
  fullFidelity?: boolean | undefined;
  metadata?: Array<ItemsTypeNotificationMetadata$Outbound> | undefined;
  description?: string | undefined;
};

/** @internal */
export const InputCriblmetrics$outboundSchema: z.ZodType<
  InputCriblmetrics$Outbound,
  z.ZodTypeDef,
  InputCriblmetrics
> = z.object({
  id: z.string().optional(),
  type: z.literal("criblmetrics"),
  disabled: z.boolean().optional(),
  pipeline: z.string().optional(),
  sendToRoutes: z.boolean().optional(),
  environment: z.string().optional(),
  pqEnabled: z.boolean().optional(),
  streamtags: z.array(z.string()).optional(),
  connections: z.array(ItemsTypeConnectionsOptional$outboundSchema).optional(),
  pq: PqType$outboundSchema.optional(),
  prefix: z.string().optional(),
  fullFidelity: z.boolean().optional(),
  metadata: z.array(ItemsTypeNotificationMetadata$outboundSchema).optional(),
  description: z.string().optional(),
});

export function inputCriblmetricsToJSON(
  inputCriblmetrics: InputCriblmetrics,
): string {
  return JSON.stringify(
    InputCriblmetrics$outboundSchema.parse(inputCriblmetrics),
  );
}
export function inputCriblmetricsFromJSON(
  jsonString: string,
): SafeParseResult<InputCriblmetrics, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InputCriblmetrics$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InputCriblmetrics' from JSON`,
  );
}
