/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { ApiScheme, ApiScheme$inboundSchema } from "./apischeme.js";
import {
  AwsTypeHeartbeatMetadata,
  AwsTypeHeartbeatMetadata$inboundSchema,
} from "./awstypeheartbeatmetadata.js";
import {
  AzureTypeHeartbeatMetadata,
  AzureTypeHeartbeatMetadata$inboundSchema,
} from "./azuretypeheartbeatmetadata.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { HBCriblInfo, HBCriblInfo$inboundSchema } from "./hbcriblinfo.js";
import {
  HeartbeatMetadata,
  HeartbeatMetadata$inboundSchema,
} from "./heartbeatmetadata.js";
import {
  HostOsTypeHeartbeatMetadata,
  HostOsTypeHeartbeatMetadata$inboundSchema,
} from "./hostostypeheartbeatmetadata.js";
import {
  KubeTypeHeartbeatMetadata,
  KubeTypeHeartbeatMetadata$inboundSchema,
} from "./kubetypeheartbeatmetadata.js";
import { NodeOsInfo, NodeOsInfo$inboundSchema } from "./nodeosinfo.js";
import {
  OsTypeHeartbeatMetadata,
  OsTypeHeartbeatMetadata$inboundSchema,
} from "./ostypeheartbeatmetadata.js";
import {
  OutpostNodeInfo,
  OutpostNodeInfo$inboundSchema,
} from "./outpostnodeinfo.js";

/**
 * Operating system metadata collected from the node.
 */
export type Os = OsTypeHeartbeatMetadata | NodeOsInfo;

export type NodeProvidedInfo = {
  /**
   * API port exposed by the node.
   */
  apiPort?: number | undefined;
  apiScheme?: ApiScheme | undefined;
  /**
   * CPU architecture.
   */
  architecture: string;
  aws?: AwsTypeHeartbeatMetadata | undefined;
  azure?: AzureTypeHeartbeatMetadata | undefined;
  /**
   * Remote <code>ip:port</code> for the worker socket.
   */
  conn_ip?: string | undefined;
  /**
   * Number of CPU cores available on the node.
   */
  cpus: number;
  cribl: HBCriblInfo;
  /**
   * Environment variables reported by the node.
   */
  env: { [k: string]: string };
  /**
   * Free disk space on the node, in bytes.
   */
  freeDiskSpace?: number | undefined;
  hostOs?: HostOsTypeHeartbeatMetadata | undefined;
  /**
   * Hostname reported by the node.
   */
  hostname: string;
  /**
   * If <code>true</code>, the node considers itself the elected captain for its group. Otherwise, <code>false</code>.
   */
  isCaptain?: boolean | undefined;
  /**
   * If <code>true</code>, the node runs in Cribl.Cloud. Otherwise, <code>false</code>.
   */
  isSaasWorker?: boolean | undefined;
  kube?: KubeTypeHeartbeatMetadata | undefined;
  /**
   * Local timestamp (in Unix time) on the node, in milliseconds.
   */
  localTime?: number | undefined;
  metadata?: HeartbeatMetadata | undefined;
  /**
   * Node.js runtime version running on the node.
   */
  node: string;
  /**
   * Operating system metadata collected from the node.
   */
  os?: OsTypeHeartbeatMetadata | NodeOsInfo | undefined;
  outpost?: OutpostNodeInfo | undefined;
  /**
   * Operating system platform.
   */
  platform: string;
  /**
   * Operating system kernel release.
   */
  release: string;
  /**
   * Total disk space on the node, in bytes.
   */
  totalDiskSpace?: number | undefined;
  /**
   * Total memory on the node, in bytes.
   */
  totalmem: number;
};

/** @internal */
export const Os$inboundSchema: z.ZodType<Os, z.ZodTypeDef, unknown> =
  smartUnion([OsTypeHeartbeatMetadata$inboundSchema, NodeOsInfo$inboundSchema]);

export function osFromJSON(
  jsonString: string,
): SafeParseResult<Os, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Os$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Os' from JSON`,
  );
}

/** @internal */
export const NodeProvidedInfo$inboundSchema: z.ZodType<
  NodeProvidedInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiPort: types.optional(types.number()),
  apiScheme: types.optional(ApiScheme$inboundSchema),
  architecture: types.string(),
  aws: types.optional(AwsTypeHeartbeatMetadata$inboundSchema),
  azure: types.optional(AzureTypeHeartbeatMetadata$inboundSchema),
  conn_ip: types.optional(types.string()),
  cpus: types.number(),
  cribl: HBCriblInfo$inboundSchema,
  env: z.record(types.string()),
  freeDiskSpace: types.optional(types.number()),
  hostOs: types.optional(HostOsTypeHeartbeatMetadata$inboundSchema),
  hostname: types.string(),
  isCaptain: types.optional(types.boolean()),
  isSaasWorker: types.optional(types.boolean()),
  kube: types.optional(KubeTypeHeartbeatMetadata$inboundSchema),
  localTime: types.optional(types.number()),
  metadata: types.optional(HeartbeatMetadata$inboundSchema),
  node: types.string(),
  os: types.optional(
    smartUnion([
      OsTypeHeartbeatMetadata$inboundSchema,
      NodeOsInfo$inboundSchema,
    ]),
  ),
  outpost: types.optional(OutpostNodeInfo$inboundSchema),
  platform: types.string(),
  release: types.string(),
  totalDiskSpace: types.optional(types.number()),
  totalmem: types.number(),
});

export function nodeProvidedInfoFromJSON(
  jsonString: string,
): SafeParseResult<NodeProvidedInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NodeProvidedInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NodeProvidedInfo' from JSON`,
  );
}
