/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  BackpressureBehaviorOptionsBlockDrop,
  BackpressureBehaviorOptionsBlockDrop$inboundSchema,
  BackpressureBehaviorOptionsBlockDrop$outboundSchema,
} from "./backpressurebehavioroptionsblockdrop.js";
import {
  CompressionLevelOptions,
  CompressionLevelOptions$inboundSchema,
  CompressionLevelOptions$outboundSchema,
} from "./compressionleveloptions.js";
import {
  CompressionOptionsHttp,
  CompressionOptionsHttp$inboundSchema,
  CompressionOptionsHttp$outboundSchema,
} from "./compressionoptionshttp.js";
import {
  DataFormatOptions,
  DataFormatOptions$inboundSchema,
  DataFormatOptions$outboundSchema,
} from "./dataformatoptions.js";
import {
  DataPageVersionOptions,
  DataPageVersionOptions$inboundSchema,
  DataPageVersionOptions$outboundSchema,
} from "./datapageversionoptions.js";
import {
  DiskSpaceProtectionOptions,
  DiskSpaceProtectionOptions$inboundSchema,
  DiskSpaceProtectionOptions$outboundSchema,
} from "./diskspaceprotectionoptions.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ItemsTypeKeyValueMetadata,
  ItemsTypeKeyValueMetadata$inboundSchema,
  ItemsTypeKeyValueMetadata$Outbound,
  ItemsTypeKeyValueMetadata$outboundSchema,
} from "./itemstypekeyvaluemetadata.js";
import {
  OrphanFileRecoveryType,
  OrphanFileRecoveryType$inboundSchema,
  OrphanFileRecoveryType$Outbound,
  OrphanFileRecoveryType$outboundSchema,
} from "./orphanfilerecoverytype.js";
import {
  ParquetVersionOptions,
  ParquetVersionOptions$inboundSchema,
  ParquetVersionOptions$outboundSchema,
} from "./parquetversionoptions.js";
import {
  RetrySettingsType,
  RetrySettingsType$inboundSchema,
  RetrySettingsType$Outbound,
  RetrySettingsType$outboundSchema,
} from "./retrysettingstype.js";

export const OutputStorjS3AuthenticationMethod = {
  /**
   * Manual
   */
  Manual: "manual",
  /**
   * Secret Key pair
   */
  Secret: "secret",
} as const;
export type OutputStorjS3AuthenticationMethod = OpenEnum<
  typeof OutputStorjS3AuthenticationMethod
>;

/**
 * Signature version to use for signing Storj requests
 */
export const OutputStorjS3SignatureVersion = {
  V2: "v2",
  V4: "v4",
} as const;
/**
 * Signature version to use for signing Storj requests
 */
export type OutputStorjS3SignatureVersion = OpenEnum<
  typeof OutputStorjS3SignatureVersion
>;

export type OutputStorjS3 = {
  /**
   * Unique ID for this output
   */
  id?: string | undefined;
  type: "storj_s3";
  /**
   * Pipeline to process data before sending out to this output
   */
  pipeline?: string | undefined;
  /**
   * Fields to automatically add to events, such as cribl_pipe. Supports wildcards.
   */
  systemFields?: Array<string> | undefined;
  /**
   * Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere.
   */
  environment?: string | undefined;
  /**
   * Tags for filtering and grouping in @{product}
   */
  streamtags?: Array<string> | undefined;
  awsAuthenticationMethod?: OutputStorjS3AuthenticationMethod | undefined;
  /**
   * Signature version to use for signing Storj requests
   */
  signatureVersion?: OutputStorjS3SignatureVersion | undefined;
  /**
   * Reuse connections between requests, which can improve performance
   */
  reuseConnections?: boolean | undefined;
  /**
   * Reject certificates that cannot be verified against a valid CA, such as self-signed certificates
   */
  rejectUnauthorized?: boolean | undefined;
  /**
   * Secret key. This value can be a constant or a JavaScript expression. Example: `${C.env.SOME_SECRET}`)
   */
  awsSecretKey?: string | undefined;
  /**
   * Name of the destination Storj bucket. Must be a JavaScript expression (which can evaluate to a constant value), enclosed in quotes or backticks. Can be evaluated only at initialization time. Example referencing a Global Variable: `myBucket-${C.vars.myVar}`
   */
  bucket: string;
  /**
   * Prefix to prepend to files before uploading. Must be a JavaScript expression (which can evaluate to a constant value), enclosed in quotes or backticks. Can be evaluated only at init time. Example referencing a Global Variable: `myKeyPrefix-${C.vars.myVar}`
   */
  destPath?: string | undefined;
  /**
   * Maximum number of parts to upload in parallel per file. Minimum part size is 5MB.
   */
  maxConcurrentFileParts?: number | undefined;
  /**
   * Disable if you can access files within the bucket but not the bucket itself
   */
  verifyPermissions?: boolean | undefined;
  /**
   * Maximum number of files that can be waiting for upload before backpressure is applied
   */
  maxClosingFilesToBackpressure?: number | undefined;
  /**
   * Filesystem location in which to buffer files, before compressing and moving to final destination. Use performant and stable storage.
   */
  stagePath: string;
  /**
   * Add the Output ID value to staging location
   */
  addIdToStagePath?: boolean | undefined;
  /**
   * Remove empty staging directories after moving files
   */
  removeEmptyDirs?: boolean | undefined;
  /**
   * JavaScript expression defining how files are partitioned and organized. Default is date-based. If blank, Stream will fall back to the event's __partition field value – if present – otherwise to each location's root directory.
   */
  partitionExpr?: string | undefined;
  /**
   * Format of the output data
   */
  format?: DataFormatOptions | undefined;
  /**
   * JavaScript expression to define the output filename prefix (can be constant)
   */
  baseFileName?: string | undefined;
  /**
   * JavaScript expression to define the output filename suffix (can be constant).  The `__format` variable refers to the value of the `Data format` field (`json` or `raw`).  The `__compression` field refers to the kind of compression being used (`none` or `gzip`).
   */
  fileNameSuffix?: string | undefined;
  /**
   * Maximum uncompressed output file size. Files of this size will be closed and moved to final output location.
   */
  maxFileSizeMB?: number | undefined;
  /**
   * Maximum amount of time to write to a file. Files open for longer than this will be closed and moved to final output location.
   */
  maxFileOpenTimeSec?: number | undefined;
  /**
   * Maximum amount of time to keep inactive files open. Files open for longer than this will be closed and moved to final output location.
   */
  maxFileIdleTimeSec?: number | undefined;
  /**
   * Maximum number of files to keep open concurrently. When exceeded, @{product} will close the oldest open files and move them to the final output location.
   */
  maxOpenFiles?: number | undefined;
  /**
   * If set, this line will be written to the beginning of each output file
   */
  headerLine?: string | undefined;
  /**
   * Buffer size used to write to a file
   */
  writeHighWaterMark?: number | undefined;
  /**
   * How to handle events when all receivers are exerting backpressure
   */
  onBackpressure?: BackpressureBehaviorOptionsBlockDrop | undefined;
  /**
   * If a file fails to move to its final destination after the maximum number of retries, move it to a designated directory to prevent further errors
   */
  deadletterEnabled?: boolean | undefined;
  /**
   * How to handle events when disk space is below the global 'Min free disk space' limit
   */
  onDiskFullBackpressure?: DiskSpaceProtectionOptions | undefined;
  /**
   * Force all staged files to close during an orderly Node shutdown. This triggers immediate upload of in-progress data — regardless of idle time, file age, or size thresholds — to minimize data loss.
   */
  forceCloseOnShutdown?: boolean | undefined;
  retrySettings?: RetrySettingsType | undefined;
  orphans?: OrphanFileRecoveryType | undefined;
  /**
   * Storj S3-compatible gateway endpoint URL (example: https://gateway.storjshare.io)
   */
  endpoint: string;
  description?: string | undefined;
  /**
   * This value can be a constant or a JavaScript expression (`${C.env.SOME_ACCESS_KEY}`)
   */
  awsApiKey?: string | undefined;
  /**
   * Select or create a stored secret that references your access key and secret key
   */
  awsSecret?: string | undefined;
  /**
   * Data compression format to apply to HTTP content before it is delivered
   */
  compress?: CompressionOptionsHttp | undefined;
  /**
   * Compression level to apply before moving files to final destination
   */
  compressionLevel?: CompressionLevelOptions | undefined;
  /**
   * Automatically calculate the schema based on the events of each Parquet file generated
   */
  automaticSchema?: boolean | undefined;
  /**
   * To add a new schema, navigate to Processing > Knowledge > Parquet Schemas
   */
  parquetSchema?: string | undefined;
  /**
   * Determines which data types are supported and how they are represented
   */
  parquetVersion?: ParquetVersionOptions | undefined;
  /**
   * Serialization format of data pages. Note that some reader implementations use Data page V2's attributes to work more efficiently, while others ignore it.
   */
  parquetDataPageVersion?: DataPageVersionOptions | undefined;
  /**
   * The number of rows that every group will contain. The final group can contain a smaller number of rows.
   */
  parquetRowGroupLength?: number | undefined;
  /**
   * Target memory size for page segments, such as 1MB or 128MB. Generally, lower values improve reading speed, while higher values improve compression.
   */
  parquetPageSize?: string | undefined;
  /**
   * Log up to 3 rows that @{product} skips due to data mismatch
   */
  shouldLogInvalidRows?: boolean | undefined;
  /**
   * The metadata of files the Destination writes will include the properties you add here as key-value pairs. Useful for tagging. Examples: "key":"OCSF Event Class", "value":"9001"
   */
  keyValueMetadata?: Array<ItemsTypeKeyValueMetadata> | undefined;
  /**
   * Statistics profile an entire file in terms of minimum/maximum values within data, numbers of nulls, etc. You can use Parquet tools to view statistics.
   */
  enableStatistics?: boolean | undefined;
  /**
   * One page index contains statistics for one data page. Parquet readers use statistics to enable page skipping.
   */
  enableWritePageIndex?: boolean | undefined;
  /**
   * Parquet tools can use the checksum of a Parquet page to verify data integrity
   */
  enablePageChecksum?: boolean | undefined;
  /**
   * How frequently, in seconds, to clean up empty directories
   */
  emptyDirCleanupSec?: number | undefined;
  /**
   * Number of directories to process in each batch during cleanup of empty directories. Minimum is 10, maximum is 10000. Higher values may require more memory.
   */
  directoryBatchSize?: number | undefined;
  /**
   * Storage location for files that fail to reach their final destination after maximum retries are exceeded
   */
  deadletterPath?: string | undefined;
  /**
   * The maximum number of times a file will attempt to move to its final destination before being dead-lettered
   */
  maxRetryNum?: number | undefined;
  /**
   * Binds 'streamtags' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'streamtags' at runtime.
   */
  __template_streamtags?: string | undefined;
  /**
   * Binds 'awsSecretKey' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'awsSecretKey' at runtime.
   */
  __template_awsSecretKey?: string | undefined;
  /**
   * Binds 'bucket' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'bucket' at runtime.
   */
  __template_bucket?: string | undefined;
  /**
   * Binds 'destPath' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'destPath' at runtime.
   */
  __template_destPath?: string | undefined;
  /**
   * Binds 'partitionExpr' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'partitionExpr' at runtime.
   */
  __template_partitionExpr?: string | undefined;
  /**
   * Binds 'format' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'format' at runtime.
   */
  __template_format?: string | undefined;
  /**
   * Binds 'baseFileName' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'baseFileName' at runtime.
   */
  __template_baseFileName?: string | undefined;
  /**
   * Binds 'fileNameSuffix' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'fileNameSuffix' at runtime.
   */
  __template_fileNameSuffix?: string | undefined;
  /**
   * Binds 'onBackpressure' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'onBackpressure' at runtime.
   */
  __template_onBackpressure?: string | undefined;
  /**
   * Binds 'endpoint' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'endpoint' at runtime.
   */
  __template_endpoint?: string | undefined;
  /**
   * Binds 'awsApiKey' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'awsApiKey' at runtime.
   */
  __template_awsApiKey?: string | undefined;
  /**
   * Binds 'compress' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'compress' at runtime.
   */
  __template_compress?: string | undefined;
  /**
   * Binds 'parquetSchema' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'parquetSchema' at runtime.
   */
  __template_parquetSchema?: string | undefined;
};

/** @internal */
export const OutputStorjS3AuthenticationMethod$inboundSchema: z.ZodType<
  OutputStorjS3AuthenticationMethod,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(OutputStorjS3AuthenticationMethod);
/** @internal */
export const OutputStorjS3AuthenticationMethod$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  OutputStorjS3AuthenticationMethod
> = openEnums.outboundSchema(OutputStorjS3AuthenticationMethod);

/** @internal */
export const OutputStorjS3SignatureVersion$inboundSchema: z.ZodType<
  OutputStorjS3SignatureVersion,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(OutputStorjS3SignatureVersion);
/** @internal */
export const OutputStorjS3SignatureVersion$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  OutputStorjS3SignatureVersion
> = openEnums.outboundSchema(OutputStorjS3SignatureVersion);

/** @internal */
export const OutputStorjS3$inboundSchema: z.ZodType<
  OutputStorjS3,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: types.optional(types.string()),
  type: types.literal("storj_s3"),
  pipeline: types.optional(types.string()),
  systemFields: types.optional(z.array(types.string())),
  environment: types.optional(types.string()),
  streamtags: types.optional(z.array(types.string())),
  awsAuthenticationMethod: types.optional(
    OutputStorjS3AuthenticationMethod$inboundSchema,
  ),
  signatureVersion: types.optional(OutputStorjS3SignatureVersion$inboundSchema),
  reuseConnections: types.optional(types.boolean()),
  rejectUnauthorized: types.optional(types.boolean()),
  awsSecretKey: types.optional(types.string()),
  bucket: types.string(),
  destPath: types.optional(types.string()),
  maxConcurrentFileParts: types.optional(types.number()),
  verifyPermissions: types.optional(types.boolean()),
  maxClosingFilesToBackpressure: types.optional(types.number()),
  stagePath: types.string(),
  addIdToStagePath: types.optional(types.boolean()),
  removeEmptyDirs: types.optional(types.boolean()),
  partitionExpr: types.optional(types.string()),
  format: types.optional(DataFormatOptions$inboundSchema),
  baseFileName: types.optional(types.string()),
  fileNameSuffix: types.optional(types.string()),
  maxFileSizeMB: types.optional(types.number()),
  maxFileOpenTimeSec: types.optional(types.number()),
  maxFileIdleTimeSec: types.optional(types.number()),
  maxOpenFiles: types.optional(types.number()),
  headerLine: types.optional(types.string()),
  writeHighWaterMark: types.optional(types.number()),
  onBackpressure: types.optional(
    BackpressureBehaviorOptionsBlockDrop$inboundSchema,
  ),
  deadletterEnabled: types.optional(types.boolean()),
  onDiskFullBackpressure: types.optional(
    DiskSpaceProtectionOptions$inboundSchema,
  ),
  forceCloseOnShutdown: types.optional(types.boolean()),
  retrySettings: types.optional(RetrySettingsType$inboundSchema),
  orphans: types.optional(OrphanFileRecoveryType$inboundSchema),
  endpoint: types.string(),
  description: types.optional(types.string()),
  awsApiKey: types.optional(types.string()),
  awsSecret: types.optional(types.string()),
  compress: types.optional(CompressionOptionsHttp$inboundSchema),
  compressionLevel: types.optional(CompressionLevelOptions$inboundSchema),
  automaticSchema: types.optional(types.boolean()),
  parquetSchema: types.optional(types.string()),
  parquetVersion: types.optional(ParquetVersionOptions$inboundSchema),
  parquetDataPageVersion: types.optional(DataPageVersionOptions$inboundSchema),
  parquetRowGroupLength: types.optional(types.number()),
  parquetPageSize: types.optional(types.string()),
  shouldLogInvalidRows: types.optional(types.boolean()),
  keyValueMetadata: types.optional(
    z.array(ItemsTypeKeyValueMetadata$inboundSchema),
  ),
  enableStatistics: types.optional(types.boolean()),
  enableWritePageIndex: types.optional(types.boolean()),
  enablePageChecksum: types.optional(types.boolean()),
  emptyDirCleanupSec: types.optional(types.number()),
  directoryBatchSize: types.optional(types.number()),
  deadletterPath: types.optional(types.string()),
  maxRetryNum: types.optional(types.number()),
  __template_streamtags: types.optional(types.string()),
  __template_awsSecretKey: types.optional(types.string()),
  __template_bucket: types.optional(types.string()),
  __template_destPath: types.optional(types.string()),
  __template_partitionExpr: types.optional(types.string()),
  __template_format: types.optional(types.string()),
  __template_baseFileName: types.optional(types.string()),
  __template_fileNameSuffix: types.optional(types.string()),
  __template_onBackpressure: types.optional(types.string()),
  __template_endpoint: types.optional(types.string()),
  __template_awsApiKey: types.optional(types.string()),
  __template_compress: types.optional(types.string()),
  __template_parquetSchema: types.optional(types.string()),
});
/** @internal */
export type OutputStorjS3$Outbound = {
  id?: string | undefined;
  type: "storj_s3";
  pipeline?: string | undefined;
  systemFields?: Array<string> | undefined;
  environment?: string | undefined;
  streamtags?: Array<string> | undefined;
  awsAuthenticationMethod?: string | undefined;
  signatureVersion?: string | undefined;
  reuseConnections?: boolean | undefined;
  rejectUnauthorized?: boolean | undefined;
  awsSecretKey?: string | undefined;
  bucket: string;
  destPath?: string | undefined;
  maxConcurrentFileParts?: number | undefined;
  verifyPermissions?: boolean | undefined;
  maxClosingFilesToBackpressure?: number | undefined;
  stagePath: string;
  addIdToStagePath?: boolean | undefined;
  removeEmptyDirs?: boolean | undefined;
  partitionExpr?: string | undefined;
  format?: string | undefined;
  baseFileName?: string | undefined;
  fileNameSuffix?: string | undefined;
  maxFileSizeMB?: number | undefined;
  maxFileOpenTimeSec?: number | undefined;
  maxFileIdleTimeSec?: number | undefined;
  maxOpenFiles?: number | undefined;
  headerLine?: string | undefined;
  writeHighWaterMark?: number | undefined;
  onBackpressure?: string | undefined;
  deadletterEnabled?: boolean | undefined;
  onDiskFullBackpressure?: string | undefined;
  forceCloseOnShutdown?: boolean | undefined;
  retrySettings?: RetrySettingsType$Outbound | undefined;
  orphans?: OrphanFileRecoveryType$Outbound | undefined;
  endpoint: string;
  description?: string | undefined;
  awsApiKey?: string | undefined;
  awsSecret?: string | undefined;
  compress?: string | undefined;
  compressionLevel?: string | undefined;
  automaticSchema?: boolean | undefined;
  parquetSchema?: string | undefined;
  parquetVersion?: string | undefined;
  parquetDataPageVersion?: string | undefined;
  parquetRowGroupLength?: number | undefined;
  parquetPageSize?: string | undefined;
  shouldLogInvalidRows?: boolean | undefined;
  keyValueMetadata?: Array<ItemsTypeKeyValueMetadata$Outbound> | undefined;
  enableStatistics?: boolean | undefined;
  enableWritePageIndex?: boolean | undefined;
  enablePageChecksum?: boolean | undefined;
  emptyDirCleanupSec?: number | undefined;
  directoryBatchSize?: number | undefined;
  deadletterPath?: string | undefined;
  maxRetryNum?: number | undefined;
  __template_streamtags?: string | undefined;
  __template_awsSecretKey?: string | undefined;
  __template_bucket?: string | undefined;
  __template_destPath?: string | undefined;
  __template_partitionExpr?: string | undefined;
  __template_format?: string | undefined;
  __template_baseFileName?: string | undefined;
  __template_fileNameSuffix?: string | undefined;
  __template_onBackpressure?: string | undefined;
  __template_endpoint?: string | undefined;
  __template_awsApiKey?: string | undefined;
  __template_compress?: string | undefined;
  __template_parquetSchema?: string | undefined;
};

/** @internal */
export const OutputStorjS3$outboundSchema: z.ZodType<
  OutputStorjS3$Outbound,
  z.ZodTypeDef,
  OutputStorjS3
> = z.object({
  id: z.string().optional(),
  type: z.literal("storj_s3"),
  pipeline: z.string().optional(),
  systemFields: z.array(z.string()).optional(),
  environment: z.string().optional(),
  streamtags: z.array(z.string()).optional(),
  awsAuthenticationMethod: OutputStorjS3AuthenticationMethod$outboundSchema
    .optional(),
  signatureVersion: OutputStorjS3SignatureVersion$outboundSchema.optional(),
  reuseConnections: z.boolean().optional(),
  rejectUnauthorized: z.boolean().optional(),
  awsSecretKey: z.string().optional(),
  bucket: z.string(),
  destPath: z.string().optional(),
  maxConcurrentFileParts: z.number().optional(),
  verifyPermissions: z.boolean().optional(),
  maxClosingFilesToBackpressure: z.number().optional(),
  stagePath: z.string(),
  addIdToStagePath: z.boolean().optional(),
  removeEmptyDirs: z.boolean().optional(),
  partitionExpr: z.string().optional(),
  format: DataFormatOptions$outboundSchema.optional(),
  baseFileName: z.string().optional(),
  fileNameSuffix: z.string().optional(),
  maxFileSizeMB: z.number().optional(),
  maxFileOpenTimeSec: z.number().optional(),
  maxFileIdleTimeSec: z.number().optional(),
  maxOpenFiles: z.number().optional(),
  headerLine: z.string().optional(),
  writeHighWaterMark: z.number().optional(),
  onBackpressure: BackpressureBehaviorOptionsBlockDrop$outboundSchema
    .optional(),
  deadletterEnabled: z.boolean().optional(),
  onDiskFullBackpressure: DiskSpaceProtectionOptions$outboundSchema.optional(),
  forceCloseOnShutdown: z.boolean().optional(),
  retrySettings: RetrySettingsType$outboundSchema.optional(),
  orphans: OrphanFileRecoveryType$outboundSchema.optional(),
  endpoint: z.string(),
  description: z.string().optional(),
  awsApiKey: z.string().optional(),
  awsSecret: z.string().optional(),
  compress: CompressionOptionsHttp$outboundSchema.optional(),
  compressionLevel: CompressionLevelOptions$outboundSchema.optional(),
  automaticSchema: z.boolean().optional(),
  parquetSchema: z.string().optional(),
  parquetVersion: ParquetVersionOptions$outboundSchema.optional(),
  parquetDataPageVersion: DataPageVersionOptions$outboundSchema.optional(),
  parquetRowGroupLength: z.number().optional(),
  parquetPageSize: z.string().optional(),
  shouldLogInvalidRows: z.boolean().optional(),
  keyValueMetadata: z.array(ItemsTypeKeyValueMetadata$outboundSchema)
    .optional(),
  enableStatistics: z.boolean().optional(),
  enableWritePageIndex: z.boolean().optional(),
  enablePageChecksum: z.boolean().optional(),
  emptyDirCleanupSec: z.number().optional(),
  directoryBatchSize: z.number().optional(),
  deadletterPath: z.string().optional(),
  maxRetryNum: z.number().optional(),
  __template_streamtags: z.string().optional(),
  __template_awsSecretKey: z.string().optional(),
  __template_bucket: z.string().optional(),
  __template_destPath: z.string().optional(),
  __template_partitionExpr: z.string().optional(),
  __template_format: z.string().optional(),
  __template_baseFileName: z.string().optional(),
  __template_fileNameSuffix: z.string().optional(),
  __template_onBackpressure: z.string().optional(),
  __template_endpoint: z.string().optional(),
  __template_awsApiKey: z.string().optional(),
  __template_compress: z.string().optional(),
  __template_parquetSchema: z.string().optional(),
});

export function outputStorjS3ToJSON(outputStorjS3: OutputStorjS3): string {
  return JSON.stringify(OutputStorjS3$outboundSchema.parse(outputStorjS3));
}
export function outputStorjS3FromJSON(
  jsonString: string,
): SafeParseResult<OutputStorjS3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutputStorjS3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutputStorjS3' from JSON`,
  );
}
