/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ae190a240c1b
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type OutpostNodeInfo = {
  groupname?: string | undefined;
  guid: string;
  host: string;
};

/** @internal */
export const OutpostNodeInfo$inboundSchema: z.ZodType<
  OutpostNodeInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  groupname: types.optional(types.string()),
  guid: types.string(),
  host: types.string(),
});
/** @internal */
export type OutpostNodeInfo$Outbound = {
  groupname?: string | undefined;
  guid: string;
  host: string;
};

/** @internal */
export const OutpostNodeInfo$outboundSchema: z.ZodType<
  OutpostNodeInfo$Outbound,
  z.ZodTypeDef,
  OutpostNodeInfo
> = z.object({
  groupname: z.string().optional(),
  guid: z.string(),
  host: z.string(),
});

export function outpostNodeInfoToJSON(
  outpostNodeInfo: OutpostNodeInfo,
): string {
  return JSON.stringify(OutpostNodeInfo$outboundSchema.parse(outpostNodeInfo));
}
export function outpostNodeInfoFromJSON(
  jsonString: string,
): SafeParseResult<OutpostNodeInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutpostNodeInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutpostNodeInfo' from JSON`,
  );
}
