/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  TagsTypePackInstallInfo,
  TagsTypePackInstallInfo$inboundSchema,
} from "./tagstypepackinstallinfo.js";

export type PackInfo = {
  author?: string | undefined;
  dependencies?: { [k: string]: string } | undefined;
  description?: string | undefined;
  displayName?: string | undefined;
  exports?: Array<string> | undefined;
  id: string;
  inputs?: number | undefined;
  isDisabled?: boolean | undefined;
  minLogStreamVersion?: string | undefined;
  outputs?: number | undefined;
  settings?: { [k: string]: any } | undefined;
  source: string;
  spec?: string | undefined;
  tags?: TagsTypePackInstallInfo | undefined;
  version?: string | undefined;
};

/** @internal */
export const PackInfo$inboundSchema: z.ZodType<
  PackInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  author: types.optional(types.string()),
  dependencies: types.optional(z.record(types.string())),
  description: types.optional(types.string()),
  displayName: types.optional(types.string()),
  exports: types.optional(z.array(types.string())),
  id: types.string(),
  inputs: types.optional(types.number()),
  isDisabled: types.optional(types.boolean()),
  minLogStreamVersion: types.optional(types.string()),
  outputs: types.optional(types.number()),
  settings: types.optional(z.record(z.any())),
  source: types.string(),
  spec: types.optional(types.string()),
  tags: types.optional(TagsTypePackInstallInfo$inboundSchema),
  version: types.optional(types.string()),
});

export function packInfoFromJSON(
  jsonString: string,
): SafeParseResult<PackInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PackInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PackInfo' from JSON`,
  );
}
