/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AdditionalPropertiesTypePipelineConfGroups,
  AdditionalPropertiesTypePipelineConfGroups$inboundSchema,
} from "./additionalpropertiestypepipelineconfgroups.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PipelineFunctionConf,
  PipelineFunctionConf$inboundSchema,
} from "./pipelinefunctionconf.js";

export type PipelineConf = {
  /**
   * Time (in ms) to wait for an async function to complete processing of a data item
   */
  asyncFuncTimeout?: number | undefined;
  /**
   * The output destination for events processed by this Pipeline
   */
  output?: string | undefined;
  description?: string | undefined;
  /**
   * Tags for filtering and grouping in @{product}
   */
  streamtags?: Array<string> | undefined;
  /**
   * List of Functions to pass data through
   */
  functions?: Array<PipelineFunctionConf> | undefined;
  groups?:
    | { [k: string]: AdditionalPropertiesTypePipelineConfGroups }
    | undefined;
};

export type Pipeline = {
  id: string;
  conf: PipelineConf;
};

/** @internal */
export const PipelineConf$inboundSchema: z.ZodType<
  PipelineConf,
  z.ZodTypeDef,
  unknown
> = z.object({
  asyncFuncTimeout: z.number().int().optional(),
  output: z.string().optional(),
  description: z.string().optional(),
  streamtags: z.array(z.string()).optional(),
  functions: z.array(PipelineFunctionConf$inboundSchema).optional(),
  groups: z.record(AdditionalPropertiesTypePipelineConfGroups$inboundSchema)
    .optional(),
});

export function pipelineConfFromJSON(
  jsonString: string,
): SafeParseResult<PipelineConf, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PipelineConf$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PipelineConf' from JSON`,
  );
}

/** @internal */
export const Pipeline$inboundSchema: z.ZodType<
  Pipeline,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  conf: z.lazy(() => PipelineConf$inboundSchema),
});

export function pipelineFromJSON(
  jsonString: string,
): SafeParseResult<Pipeline, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Pipeline$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Pipeline' from JSON`,
  );
}
