/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Configuration specific to the Pipeline Function.
 */
export type LakeExportConfiguration = {
  /**
   * Id of the search job this function is running on.
   */
  searchJobId: string;
  /**
   * Name of the dataset
   */
  dataset: string;
  /**
   * Name of the lake
   */
  lake?: string | undefined;
  /**
   * Tee results to search. When set to true results will be shipped instead of stats
   */
  tee?: boolean | undefined;
  /**
   * How often are stats flushed in ms
   */
  flushMs?: number | undefined;
  /**
   * Disables generation of intermediate stats. When true stats will be emitted only on end
   */
  suppressPreviews?: boolean | undefined;
};

export type PipelineFunctionLakeExport = {
  /**
   * JavaScript expression that selects data to pass through the Function.
   */
  filter?: string | undefined;
  /**
   * Identifier of the Function. Always <code>lake_export</code>
   */
  id: "lake_export";
  /**
   * Brief description of the Pipeline function.
   */
  description?: string | undefined;
  /**
   * If <code>true</code>, disable the Pipeline function so that events are not passed through it. Otherwise, <code>false</code>.
   */
  disabled?: boolean | undefined;
  /**
   * If <code>true</code>, stop passing events to downstream Pipeline Functions after the Function executes. Otherwise, <code>false</code>.
   */
  final?: boolean | undefined;
  /**
   * Configuration specific to the Pipeline Function.
   */
  conf: LakeExportConfiguration;
  /**
   * Unique identifier of the group that contains the Pipeline Function.
   */
  groupId?: string | undefined;
};

/** @internal */
export const LakeExportConfiguration$inboundSchema: z.ZodType<
  LakeExportConfiguration,
  z.ZodTypeDef,
  unknown
> = z.object({
  searchJobId: types.string(),
  dataset: types.string(),
  lake: types.optional(types.string()),
  tee: types.optional(types.boolean()),
  flushMs: types.optional(types.number()),
  suppressPreviews: types.optional(types.boolean()),
});
/** @internal */
export type LakeExportConfiguration$Outbound = {
  searchJobId: string;
  dataset: string;
  lake?: string | undefined;
  tee?: boolean | undefined;
  flushMs?: number | undefined;
  suppressPreviews?: boolean | undefined;
};

/** @internal */
export const LakeExportConfiguration$outboundSchema: z.ZodType<
  LakeExportConfiguration$Outbound,
  z.ZodTypeDef,
  LakeExportConfiguration
> = z.object({
  searchJobId: z.string(),
  dataset: z.string(),
  lake: z.string().optional(),
  tee: z.boolean().optional(),
  flushMs: z.number().optional(),
  suppressPreviews: z.boolean().optional(),
});

export function lakeExportConfigurationToJSON(
  lakeExportConfiguration: LakeExportConfiguration,
): string {
  return JSON.stringify(
    LakeExportConfiguration$outboundSchema.parse(lakeExportConfiguration),
  );
}
export function lakeExportConfigurationFromJSON(
  jsonString: string,
): SafeParseResult<LakeExportConfiguration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LakeExportConfiguration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LakeExportConfiguration' from JSON`,
  );
}

/** @internal */
export const PipelineFunctionLakeExport$inboundSchema: z.ZodType<
  PipelineFunctionLakeExport,
  z.ZodTypeDef,
  unknown
> = z.object({
  filter: types.optional(types.string()),
  id: types.literal("lake_export"),
  description: types.optional(types.string()),
  disabled: types.optional(types.boolean()),
  final: types.optional(types.boolean()),
  conf: z.lazy(() => LakeExportConfiguration$inboundSchema),
  groupId: types.optional(types.string()),
});
/** @internal */
export type PipelineFunctionLakeExport$Outbound = {
  filter?: string | undefined;
  id: "lake_export";
  description?: string | undefined;
  disabled?: boolean | undefined;
  final?: boolean | undefined;
  conf: LakeExportConfiguration$Outbound;
  groupId?: string | undefined;
};

/** @internal */
export const PipelineFunctionLakeExport$outboundSchema: z.ZodType<
  PipelineFunctionLakeExport$Outbound,
  z.ZodTypeDef,
  PipelineFunctionLakeExport
> = z.object({
  filter: z.string().optional(),
  id: z.literal("lake_export"),
  description: z.string().optional(),
  disabled: z.boolean().optional(),
  final: z.boolean().optional(),
  conf: z.lazy(() => LakeExportConfiguration$outboundSchema),
  groupId: z.string().optional(),
});

export function pipelineFunctionLakeExportToJSON(
  pipelineFunctionLakeExport: PipelineFunctionLakeExport,
): string {
  return JSON.stringify(
    PipelineFunctionLakeExport$outboundSchema.parse(pipelineFunctionLakeExport),
  );
}
export function pipelineFunctionLakeExportFromJSON(
  jsonString: string,
): SafeParseResult<PipelineFunctionLakeExport, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PipelineFunctionLakeExport$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PipelineFunctionLakeExport' from JSON`,
  );
}
