/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { CapturedEvent, CapturedEvent$inboundSchema } from "./capturedevent.js";
import { CaptureStats, CaptureStats$inboundSchema } from "./capturestats.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PreviewResponse = {
  /**
   * Total count of captured events.
   */
  count: number;
  /**
   * Array of events captured during Pipeline preview.
   */
  items: Array<CapturedEvent>;
  message?: string | undefined;
  profile?: string | undefined;
  stats?: CaptureStats | undefined;
  stderr: string;
};

/** @internal */
export const PreviewResponse$inboundSchema: z.ZodType<
  PreviewResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  count: types.number(),
  items: z.array(CapturedEvent$inboundSchema),
  message: types.optional(types.string()),
  profile: types.optional(types.string()),
  stats: types.optional(CaptureStats$inboundSchema),
  stderr: types.string(),
});

export function previewResponseFromJSON(
  jsonString: string,
): SafeParseResult<PreviewResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewResponse' from JSON`,
  );
}
