/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  HealthStringType,
  HealthStringType$inboundSchema,
} from "./healthstringtype.js";
import { StatusError, StatusError$inboundSchema } from "./statuserror.js";
import {
  WorkerPQStatus,
  WorkerPQStatus$inboundSchema,
} from "./workerpqstatus.js";

/**
 * Runtime status: health, metrics, and optional persistent-queue info. Fields may be absent when data is unavailable.
 */
export type StatusType = {
  error?: StatusError | undefined;
  health?: HealthStringType | undefined;
  /**
   * Metrics data for the Source or Destination.
   */
  metrics?: { [k: string]: any } | undefined;
  pq?: WorkerPQStatus | undefined;
  /**
   * Timestamp (in Unix time) when the status was last updated.
   */
  timestamp?: number | undefined;
  /**
   * Set to prefer status from the LB process, not from the worker process.
   */
  useStatusFromLB?: boolean | undefined;
};

/** @internal */
export const StatusType$inboundSchema: z.ZodType<
  StatusType,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: types.optional(StatusError$inboundSchema),
  health: types.optional(HealthStringType$inboundSchema),
  metrics: types.optional(z.record(z.any())),
  pq: types.optional(WorkerPQStatus$inboundSchema),
  timestamp: types.optional(types.number()),
  useStatusFromLB: types.optional(types.boolean()),
});

export function statusTypeFromJSON(
  jsonString: string,
): SafeParseResult<StatusType, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StatusType$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StatusType' from JSON`,
  );
}
