name: Internal remote workflow

permissions:
  contents: write

on:
  workflow_run:
    workflows: ["Publish alpha SDK based on dev-remote branch"]
    types: [completed]

concurrency:
  group: publish-dev-remote
  cancel-in-progress: false

jobs:
  gate:
    runs-on: ubuntu-latest
    outputs:
      should_publish: ${{ steps.decide.outputs.should_publish }}
    steps:
      - id: decide
        run: |
          if [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            echo "Triggered by workflow_run"
            concl="${{ github.event.workflow_run.conclusion }}"
            branch="${{ github.event.workflow_run.head_branch }}"
            echo "Conclusion: $concl, Branch: $branch"
            if [[ "$concl" == "success" && "$branch" == "dev-remote" ]]; then
              echo "should_publish=true" >> "$GITHUB_OUTPUT"
            else
              echo "should_publish=false" >> "$GITHUB_OUTPUT"
            fi
          else
            # push path: keep your original commit-message filter
            msg="${{ github.event.head_commit.message || '' }}"
            echo "Triggered by push. Head commit message: $msg"
            if [[ "$msg" == *"chore(sdk): generate prerelease"* ]]; then
              echo "should_publish=true" >> "$GITHUB_OUTPUT"
            else
              echo "should_publish=false" >> "$GITHUB_OUTPUT"
            fi
          fi

  publish:
    needs: gate
    if: needs.gate.outputs.should_publish == 'true'
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@57452fc95969792de6734a91400a24aeb409964c
    with:
      target: cribl-control-plane
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
