name: Test
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
"on":
  pull_request:
    branches:
      - main
    paths:
      - '**'
  workflow_dispatch:
    inputs:
      target:
        description: Provided SDK target to run tests for, (all) is valid
        type: string
jobs:
  test:
    uses: michalbiesek/sdk-generation-action/.github/workflows/sdk-publish.yaml@feat-fix-npm-read
    with:
      target: ${{ github.event.inputs.target || 'cribl-control-plane' }}
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
